repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
        - id: check-added-large-files
        - id: check-case-conflict
        - id: check-yaml
        - id: detect-private-key
        - id: end-of-file-fixer
        - id: no-commit-to-branch
        - id: trailing-whitespace

    - repo: https://github.com/tomas-krupa/qmlformat-hook.git
      rev: 1.2.0
      hooks:
        - id: qmlformat
          additional_dependencies:
            - PySide6-Essentials==6.10.2

# Specific part for https://pre-commit.ci
ci:
  autofix_commit_msg: "[pre-commit.ci] Automatic updates applied by git hooks."
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] Automatic updates applied by git hooks."
  autoupdate_schedule: monthly
  skip: []
  submodules: false
