name: 🚀 Release

on:
  push:
    tags:
      - '*'

jobs:

  release:

    name: 👷 GitHub Release
    runs-on: ubuntu-latest

    if: github.ref_type == 'tag'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip the QField plugin
        run: |
          cd qfield-plugin-qchat
          zip -r "../qfchat-${GITHUB_REF#refs/tags/}.zip" ./*
          zip -r "../qfchat-latest.zip" ./*

      - name: Create GitHub Release with assets
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            qfchat-${GITHUB_REF#refs/tags/}.zip
            qfchat-latest.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
