name: 🚀 Release

on:
  push:
    tags:
      - '*'

jobs:

  release:

    name: 👷 GitHub Release
    runs-on: ubuntu-latest

    if: github.ref_type == 'tag'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Zip the QField plugin
        run: |
          cd qfield-plugin-qchat
          zip -r "../qfchat-${GITHUB_REF#refs/tags/}.zip" ./*
          zip -r "../qfchat-latest.zip" ./*

      - name: Create GitHub Release with assets
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
          files: |
            qfchat-${GITHUB_REF#refs/tags/}.zip
            qfchat-latest.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send notification on matrix
        id: matrix-notification
        uses: fadenb/matrix-chat-message@v0.0.6
        with:
          homeserver: ${{ secrets.PUBLISH_MATRIX_HOMESERVER }}
          token: ${{ secrets.PUBLISH_MATRIX_TOKEN }}
          channel: ${{ secrets.PUBLISH_MATRIX_CHANNEL }}
          message: |
            💬 New QChat QField plugin version: ${{ github.ref_name }} !\
            -> https://github.com/geotribu/qchat-qfield-plugin/releases
